### ISSUE TITLE
Use masonry in my project

### ISSUE THREAD

**Issue by Tommy10802** [colepatrickturner/react-components#5]
Hello, first thank for great article and example code of masonry.
I need exactly component like this in my project. It is possible to use it from this example code which you have in repository?

**Comment by coleturner** [comment]
Hey @Tommy10802 ,

Thanks for writing! You can copy/paste the code here and configure it to your project. Support for this component is limited (which is why I don't publish it) but if you run into any troubles there are a couple of open/closed issues - or if anything else comes up feel free to ask.

Cheers!
